#**GATEWAY: DEJAMOS EL PUERTO EN 0 
server:
  port: 0
  error:
    include-stacktrace: never
  forward-headers-strategy: framework

spring:
  application:
    name: ms-usuarios
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.add.type.headers": false
    consumer:
      group-id: ms-usuarios
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "cl.tripplanner.common.event"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/usuarios
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#***** JWT *****
#Contraseña desencriptada: "tokenSecretKeyTurismo2026TripplannerSecurity"
jwt:
  secret: "dG9rZW5TZWNyZXRLZXlUdXJpc21vMjAyNlRyaXBwbGFubmVyU2VjdXJpdHk="
  expiration-ms: 3600000


#http://localhost:9010/swagger-ui/index.html <- RUTA PARA PROBAR SWAGGER-UI
# [SWAGGER-INI] 
# Configuración de SpringDoc/Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /docs/usuarios/v3/api-docs/swagger-config
    url: /docs/usuarios/v3/api-docs
# [SWAGGER-FIN] 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60


#Codigo desarrolllo dev
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    version: "@project.version@"
    description: "Microservicio de gestión de usuarios"

# ════════════════════════════════════════════════════════════
# PERFIL: Desarrollo
# ════════════════════════════════════════════════════════════
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# MOVIDO AQUÍ PARA ASEGURAR QUE SE ACTIVE EN DEV
logging:
  level:
    root: INFO
    cl.tripplanner: DEBUG                   # <--- Esto activa TODO tu código
    org.springframework.kafka: INFO
    org.apache.kafka.clients: WARN
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

# ════════════════════════════════════════════════════════════
# PERFIL: Producción
# ════════════════════════════════════════════════════════════
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO
    cl.tripplanner: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
      #bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}